name: lint / PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  validate:
    uses: ./.github/workflows/shared--conventional-commits.yaml
    with:
      subjects: ${{ github.event.pull_request.title }}
      label: PR title
