name: workflow / conftest

on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: conftest test -o github -p conftest/workflow .github/workflows
