name: workflow / conftest

on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: conftest test -o github -p conftest/workflow .github/workflows
